[settings]
node.gpg_verify = false

[tools]
# Runtimes
node = "lts"
python = "latest"
go = "latest"

# Shell tools
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
zoxide = "latest"
delta = "latest"
sd = "latest"

# Dev tools
neovim = "latest"
lazygit = "latest"
just = "latest"
jq = "latest"
yq = "latest"
github-cli = "latest"
kubectl = "latest"
"github:BurntSushi/ripgrep" = "latest"

# Prompt
oh-my-posh = "latest"

# Package managers
pnpm = "latest"
