# Set palette
palette = 'catppuccin_macchiato'

format = """
$hostname \
[](white)\
$os\
[](bg:blue fg:white)\
[$directory](bg:blue fg:white)\
${custom.inverted_git}\
([](fg:blue bg:green)\
$git_branch$git_status$git_metrics\
[](fg:green))\
$fill\
([[$nodejs](fg:white)](fg:surface1 bg:none))\
([[$java](fg:white)](fg:surface1 bg:none))\
([[$dotnet](fg:white)](fg:surface1 bg:none))\
([[$golang](fg:white)](fg:surface1 bg:none))\
([[$rust](fg:white)](fg:surface1 bg:none))\
([[$dart](fg:white)](fg:surface1 bg:none))\
([[$julia](fg:white)](fg:surface1 bg:none))\
([[$ruby](fg:white)](fg:surface1 bg:none))\
([[$python](fg:white)](fg:surface1 bg:none))
 $character
"""

[hostname]
ssh_only = true
ssh_symbol = '󰖟'
format = '[](bg:none fg:flamingo)[$ssh_symbol](bold fg:surface0 bg:flamingo)[$hostname](bold bg:flamingo fg:surface0)[](bg:none fg:flamingo)'

[kubernetes]
format = '[[󱃾](fg:sky)$context \($namespace\)]($style)'
style = 'bg:surface1 fg:subtext1'

[ruby]
format = '[$symbol $version]($style)'
symbol = '[󰴭](fg:red bg:surface1)'
style = 'bg:surface1 fg:subtext1'

[julia]
format = '[$symbol $version]($style)'
symbol = '[](fg:white bg:surface1)'
style = 'bg:surface1 fg:subtext1'


[dart]
format = '[$symbol $version]($style)'
symbol = '[](fg:sky bg:surface1)'
style = 'bg:surface1 fg:subtext1'

[rust]
format = '[$symbol $version]($style)'
symbol = '[󱘗](fg:red bg:surface1)'
style = 'bg:surface1 fg:subtext1'


[golang]
format = '[$symbol $version]($style)'
symbol = '[󰟓](fg:green bg:surface1)'
style = 'bg:surface1 fg:subtext1'

[dotnet]
format = '[$symbol $version]($style)'
symbol = '[](fg:blue bg:surface1)'
style = 'bg:surface1 fg:subtext1'

[java]
format = '[$symbol $version]($style)'
symbol = '[](fg:blue bg:surface1)'
style = 'bg:surface1 fg:subtext1'

[python]
format = '[$symbol $version]($style)'
symbol = '[](fg:yellow bg:surface1)'
style = 'bg:surface1 fg:subtext1'

[nodejs]
format = '[$symbol $version]($style)'
symbol = '[](fg:green bg:surface1)'
style = 'bg:surface1 fg:subtext1'


[custom.inverted_git]
# when = 'not_git_repo'
command = '' # shows output of command
when = '''test $((git -C "$directory" rev-parse --is-inside-work-tree >/dev/null 2>/dev/null && echo "false") || echo "true") = "true"'''
format = '[]($style)'
style = 'fg:blue bg:none'

[directory]
format = "[  $path ]($style)"
style = "fg:white bg:blue"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:mantle bg:green"

[git_status]
format = '[$all_status]($style)'
style = "fg:mantle bg:green"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:mantle bg:green"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "


# Disable the blank line at the start of the prompt
# add_newline = true

[character]
success_symbol = '[](bold )'
error_symbol = '[](bold red)'

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:blue"
style_root = "bg:blue"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:white fg:overlay0"
disabled = false # Disabled by default

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

# Now define the palette
[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
white = "#FFFFFF"
