#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
osc99 = true

[palette]
os = "#ACB0BE"
closer = "p:os"
pink = "#F5BDE6"
lavender = "#B7BDF8"
blue = "#8AADF4"
peach = "#f5a97f"
yellow = "#eed49f"
text = "#cad3f5"
crust = "#181926"
mantle = "#1e2030"
base = "#24273a"
green = "#a6da95"
teal = "#8bd5ca"
maroon = "#ee99a0"
red = "#ed8796"
flamingo = "#dd7878"
mauve = "#c6a0f6"
sapphire = "#7dc4e4"
surface0 = "#363a4f"
surface2 = "#5b6078"
sky = "#91d7e3"

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'session'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ' '
template = '{{ if .SSHSession }}  {{.HostName}} {{ end }}'
background = 'p:teal'
foreground = 'p:base'


[[blocks.segments]]
type = 'session'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ' '
template = '{{ if .Root }}{{ end }}'
background = 'p:maroon'
foreground = 'p:base'


[[blocks.segments]]
type = 'os'
style = 'diamond'
leading_diamond = ''
template = ' {{ if .WSL }}WSL {{ end }}{{.Icon}} '
background_templates = [
  '{{if contains "ubuntu" .OS}}p:peach{{end}}',
  '{{if contains "windows" .OS}}p:blue{{end}}',
  '{{if contains "nixos" .OS}}p:lavender{{end}}',
]
foreground = 'p:crust'
properties = { windows = '' }

[[blocks.segments]]
type = 'path'
style = 'powerline'
powerline_symbol = ''
template = '  {{ .Path }} '
background = 'p:mantle'
foreground = 'p:text'
properties = { style = 'full', home_icon = '~' }


[[blocks.segments]]
type = 'git'
style = 'powerline'
powerline_symbol = ''
background_templates = [
  '{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}',
  '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:green{{ end }}',
  '{{ if gt .Ahead 0 }}p:mauve{{ end }}',
  '{{ if gt .Behind 0 }}p:mauve{{ end }}',
]
template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{ .BranchStatus }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<p:red>  {{ .Staging.String }}</>{{ end }} '
background = 'p:flamingo'
foreground = 'p:base'

[blocks.segments.properties]
branch_icon = ' '
fetch_status = true
fetch_upstream_icon = true


[[blocks]]
type = 'prompt'
alignment = 'right'

[[blocks.segments]]
type = 'node'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ''
template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'
background = 'p:surface0'
foreground = 'p:green'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
fetch_package_manager = true

[[blocks.segments]]
type = 'python'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ''
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
background = 'p:surface0'
foreground = 'p:yellow'

[[blocks.segments]]
type = 'java'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ''
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
background = 'p:surface0'
foreground = 'p:red'

[[blocks.segments]]
type = 'dotnet'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ''
template = ' {{ if .Unsupported }}{{ else }}{{ .Full }}{{ end }}'
background = 'p:surface0'
foreground = 'p:sapphire'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'go'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ''
template = 'ﳑ {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
background = 'p:surface0'
foreground = 'p:sky'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'rust'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ''
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
background = 'p:surface0'
foreground = 'p:peach'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'kubectl'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ''
template = 'ﴱ {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}'
background = 'p:surface0'
foreground = 'p:blue'
Text = ''
Duration = 0
NameLength = 0

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'status'
style = 'plain'
foreground_templates = [
  "{{if gt .Code 0}}p:red{{end}}",
  "{{if eq .Code 0}}p:text{{end}}",
]
template = ' '
background = 'transparent'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
always_enabled = true


[transient_prompt]
newline = true
foreground_templates = [
  "{{if gt .Code 0}}p:red{{end}}",
  "{{if eq .Code 0}}p:text{{end}}",
]
background = 'transparent'
template = ' '
filler = '\n '

[secondary_prompt]
foreground = "p:surface2"
background = "transparent"
template = ' '
