#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
osc99 = true

[palette]
os = "#ACB0BE"
closer = "p:os"
pink = "#F5BDE6"
lavender = "#B7BDF8"
blue = "#8AADF4"
peach = "#fe640b"
yellow = "#df8e1d"
text = "#4c4f69"
crust = "#dce0e8"
base = "#eff1f5"
green = "#40a02b"
teal = "#179299"
maroon = "#e64553"


[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
type = 'session'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ' '
template = '{{ if .SSHSession }} {{.Hostname}}{{ end }}'
background = 'p:teal'
foreground = 'p:base'


[[blocks.segments]]
type = 'session'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ' '
template = '{{ if .Root }}{{ end }}'
background = 'p:maroon'
foreground = 'p:base'


[[blocks.segments]]
type = 'os'
style = 'diamond'
leading_diamond = ''
template = ' {{ if .WSL }}WSL {{ end }}{{.Icon}} '
background = 'p:text'
foreground = 'p:base'
Duration = 0
NameLength = 0
properties = { windows = '' }

[[blocks.segments]]
type = 'path'
style = 'powerline'
powerline_symbol = ''
template = '  {{ .Path }}'
background_templates = [
  '{{if contains "ubuntu" .OS}}p:yellow{{end}}',
  '{{if contains "windows" .OS}}p:blue{{end}}',
  '{{if contains "nixos" .OS}}p:lavender{{end}}',
]
foreground = 'p:text'
Text = ''
Duration = 0
NameLength = 0
properties = { style = 'full', home_icon = '~' }


[[blocks.segments]]
type = 'git'
style = 'powerline'
powerline_symbol = ''
background_templates = [
  '{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb95{{ end }}',
  '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c5e478{{ end }}',
  '{{ if gt .Ahead 0 }}#C792EA{{ end }}',
  '{{ if gt .Behind 0 }}#C792EA{{ end }}',
]
template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{ .BranchStatus }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350>  {{ .Staging.String }}</>{{ end }} '
background = '#FFFB38'
foreground = '#011627'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
branch_icon = ' '
fetch_status = true
fetch_upstream_icon = true


[[blocks]]
type = 'prompt'
alignment = 'right'

[[blocks.segments]]
type = 'node'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ''
template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'
background = '#303030'
foreground = '#3C873A'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
fetch_package_manager = true

[[blocks.segments]]
type = 'python'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ''
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
background = '#306998'
foreground = '#FFE873'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'java'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ''
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
background = '#0e8ac8'
foreground = '#ec2729'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'dotnet'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ''
template = ' {{ if .Unsupported }}{{ else }}{{ .Full }}{{ end }}'
background = '#0e0e0e'
foreground = '#0d6da8'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'go'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ''
template = 'ﳑ {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
background = '#ffffff'
foreground = '#06aad5'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'rust'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ''
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
background = '#f3f0ec'
foreground = '#925837'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'kubectl'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ''
template = 'ﴱ {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}'
background = '#316ce4'
foreground = '#ffffff'
Text = ''
Duration = 0
NameLength = 0

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'status'
style = 'plain'
foreground_templates = ['{{ if gt .Code 0 }}#ef5350{{ end }}']
template = ' '
background = 'default'
foreground = '#e0f8ff'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
always_enabled = true
